export const DEPARTMENT_IDS = ["creator", "fund", "operations", "knowledge", "planning", "engineering"] as const;
export type DepartmentId = typeof DEPARTMENT_IDS[number];
export type MetricAvailability = "CONFIRMED" | "PARTIAL" | "UNKNOWN";
export type DepartmentMetric = { metric: string; label: string; value: number | null; availability: MetricAvailability; unit?: string; asOf?: string; source: string };
export type DepartmentReadModel = {
  id: DepartmentId; name: string; northStar: DepartmentMetric; outcomes: DepartmentMetric[]; operations: DepartmentMetric[];
  currentWork: string[]; problems: string[]; suggestions: Array<{ observation: string; interpretation: string; suggestion: string }>;
  executionAuthority?: "HUMAN_ONLY"; aiExecutionAllowed?: false;
};
type Json = Record<string, any>;
const arr = (v: unknown): any[] => Array.isArray(v) ? v : [];
const n = (v: unknown): number | null => typeof v === "number" && Number.isFinite(v) ? v : null;
const metric = (key: string, label: string, value: unknown, source: string, unit?: string, availability?: MetricAvailability): DepartmentMetric => ({ metric: key, label, value: n(value), availability: availability ?? (n(value) === null ? "UNKNOWN" : "CONFIRMED"), unit, source });

export function buildDepartmentReadModel(id: DepartmentId, data: Json, asOf = new Date().toISOString()): DepartmentReadModel {
  const withAsOf = (m: DepartmentMetric) => ({ ...m, asOf });
  if (id === "creator") {
    const outcome = data.economics?.outcome ?? {}; const content = data.content ?? {}; const opportunities = arr(data.opportunities?.opportunities);
    const revenue = n(outcome.revenueYen); const published = n(content.publishedCount);
    const revenuePerContent = revenue !== null && published !== null && published > 0 ? revenue / published : null;
    const status = outcome.revenueStatus === "CONFIRMED" && outcome.costStatus === "CONFIRMED" ? "CONFIRMED" : outcome.revenueStatus === "UNKNOWN" ? "UNKNOWN" : "PARTIAL";
    return { id, name: "Creator", northStar: withAsOf(metric("creator_profit", "Creator Profit", outcome.profitYen, "Company Revenue + Cost Ledger", "円", status)), outcomes: [metric("revenue", "Revenue", revenue, "Revenue Ledger", "円", outcome.revenueStatus), metric("profit", "Profit", outcome.profitYen, "Economic Outcome", "円", status), metric("roi", "ROI", outcome.roi, "Economic Outcome", "x", status), metric("conversions", "Conversions", content.conversions, "Content Ledger"), metric("revenue_per_content", "Revenue / Content", revenuePerContent, "Revenue + Content", "円")].map(withAsOf), operations: [["published", "Published", content.publishedCount], ["x_impressions", "X Impressions", content.xImpressions], ["note_views", "Note Views", content.noteViews], ["link_clicks", "Link Clicks", content.linkClicks], ["cta_clicks", "CTA Clicks", content.ctaClicks], ["ctr", "CTR", content.derived?.ctr], ["cta_ctr", "CTA CTR", content.derived?.ctaCtr], ["conversion_rate", "Conversion Rate", content.derived?.conversionRate], ["rpm", "Revenue / 1000 Impressions", content.derived?.revenuePerThousandImpressions]].map(([k,l,v]) => withAsOf(metric(String(k), String(l), v, "Content Dashboard"))), currentWork: opportunities.slice(0, 5).map((x) => String(x.title ?? x.name ?? "Creator opportunity")), problems: revenue === null ? ["Revenue data is missing"] : [], suggestions: revenue === null ? [{ observation: "Revenue is UNKNOWN", interpretation: "収益性を評価できません", suggestion: "Revenue/Costの確認済みFactを記録してください" }] : [] };
  }
  if (id === "fund") {
    const perf = data.performance?.performance ?? data.transactions?.performance ?? {}; const recs = arr(data.recommendations?.recommendations); const decisions = arr(data.decisions?.decisions); const tx = arr(data.transactions?.transactions); const learnings = arr(data.learning?.learnings);
    const decisionRequired = recs.filter((r) => !decisions.some((d) => d.recommendationId === r.id)).length;
    return { id, name: "Fund", northStar: withAsOf(metric("asset_growth", "Asset Growth", null, "Fund Performance", "%")), outcomes: [metric("portfolio_value", "Portfolio Value", null, "Holdings", "円"), metric("realized_pl", "Realized P/L", perf.realized?.net, "Transaction Accounting", "円", perf.realized?.status), metric("unrealized_pl", "Unrealized P/L", perf.unrealized?.pnlJpy, "Holdings", "円", perf.unrealized?.status)].map(withAsOf), operations: [metric("recommendations", "Recommendations", recs.length, "Fund Recommendations"), metric("decision_required", "Decision Required", decisionRequired, "Recommendations + Decisions"), metric("transactions", "Transactions", tx.length, "Transaction Ledger"), metric("allocation", "Allocation", null, "Portfolio"), metric("concentration", "Concentration", null, "Portfolio"), metric("approved_learnings", "Approved Learnings", learnings.filter((x) => x.status === "approved").length, "Fund Learning")].map(withAsOf), currentWork: recs.slice(0, 5).map((r) => `${r.ticker ?? "Fund"}: ${r.action ?? "UNKNOWN"}`), problems: recs.filter((r) => r.action === "WAIT_DATA" || r.executionBlocked).map((r) => `${r.ticker ?? "Fund"}: data/policy blocked`), suggestions: [], executionAuthority: "HUMAN_ONLY", aiExecutionAllowed: false };
  }
  if (id === "operations") {
    const m = data.metrics ?? {}; const insufficient = m.sufficientData === false;
    const availability = insufficient ? "PARTIAL" : undefined;
    const ops = [["automation", "Automation Rate", m.automationRate, "%"], ["intervention", "CEO Intervention Rate", m.ceoInterventionRate, "%"], ["failure_rate", "Failure Rate", m.failureRate, "%"], ["success", "Success", m.success], ["failure", "Failure", m.failure], ["skipped", "Skipped", m.skipped], ["latency", "Average Latency", m.avgLatencyMs, "ms"], ["cost", "AI Cost", m.totalCostUsd, "USD"]].map(([k,l,v,u]) => withAsOf(metric(String(k), String(l), v, "Company Events", String(u ?? ""), availability)));
    return { id, name: "Operations", northStar: ops[0], outcomes: ops.slice(0,3), operations: ops.slice(3), currentWork: arr(data.execution?.state?.missions).filter((x) => ["ACTIVE","EXECUTING"].includes(x.status)).slice(0,5).map((x) => String(x.title)), problems: arr(data.execution?.state?.missions).filter((x) => ["BLOCKED","FAILED"].includes(x.status)).map((x) => String(x.title)), suggestions: [] };
  }
  if (id === "knowledge") { const k = data.knowledge?.kpis ?? {}; return { id, name: "Knowledge", northStar: withAsOf(metric("new_knowledge", "New Knowledge", k.addedThisWeek, "Knowledge Index")), outcomes: [metric("pending", "Pending", k.review, "Knowledge Candidates"), metric("promoted", "Promoted", null, "Knowledge Index"), metric("merged", "Merged", null, "Knowledge Index"), metric("opportunity", "Knowledge → Opportunity", null, "Opportunity Store"), metric("content", "Knowledge → Content", null, "Content Candidate"), metric("revenue", "Revenue-linked Knowledge", null, "Revenue Ledger")].map(withAsOf), operations: [metric("total", "Knowledge", k.knowledge, "Knowledge Index"), metric("candidates", "Candidates", k.candidate, "Knowledge Candidates")].map(withAsOf), currentWork: arr(data.knowledge?.candidates).slice(0,5).map((x) => String(x.frontmatter?.title ?? x.path ?? "Knowledge candidate")), problems: k.review > 0 ? [`${k.review}件のHuman Review待ち`] : [], suggestions: [] }; }
  if (id === "planning") { const tasks = arr(data.planning?.plan?.tasks); const missions = arr(data.execution?.state?.missions); return { id, name: "Planning", northStar: withAsOf(metric("today_tasks", "Today Tasks", tasks.length, "Daily Plan")), outcomes: [metric("priority_a", "Priority A", tasks.filter((x) => x.priority === 1).length, "Daily Plan"), metric("priority_b", "Priority B", tasks.filter((x) => x.priority === 2).length, "Daily Plan"), metric("priority_c", "Priority C", tasks.filter((x) => x.priority >= 3).length, "Daily Plan")].map(withAsOf), operations: [metric("active", "Active Missions", missions.filter((x) => ["ACTIVE","EXECUTING"].includes(x.status)).length, "Mission Store"), metric("completed", "Completed Missions", missions.filter((x) => x.status === "COMPLETED").length, "Mission Store"), metric("blocked", "Blocked Missions", missions.filter((x) => ["BLOCKED","FAILED"].includes(x.status)).length, "Mission Store"), metric("overdue", "Overdue", tasks.filter((x) => !x.done && x.deadline && x.deadline < asOf).length, "Daily Plan")].map(withAsOf), currentWork: tasks.filter((x) => !x.done).slice(0,5).map((x) => String(x.title)), problems: missions.filter((x) => ["BLOCKED","FAILED"].includes(x.status)).map((x) => String(x.title)), suggestions: [] }; }
  const items = arr(data.engineering?.items); const githubAvailable = data.engineering?.available === true; return { id, name: "Engineering", northStar: withAsOf(metric("worker", "Worker Availability", null, "Engineering Runtime")), outcomes: [metric("pr_ready", "PR Ready", null, "GitHub Pull Requests"), metric("ci_success", "CI Success", null, "GitHub Checks"), metric("ci_failure", "CI Failure", null, "GitHub Checks")].map(withAsOf), operations: [metric("queued", "Queued", githubAvailable ? items.length : null, "GitHub Issues"), metric("running", "Running", null, "Engineering Runtime"), metric("blocked", "Blocked", null, "Engineering Runtime"), metric("fix_attempts", "Fix Attempts", null, "Engineering Runtime"), metric("last_activity", "Last Activity", null, "GitHub")].map(withAsOf), currentWork: items.slice(0,5).map((x) => String(x.title)), problems: [], suggestions: [] };
}

export type DepartmentDirectiveDraft = { id: string; department: DepartmentId; instruction: string; goal?: string; priority: "A"|"B"|"C"; deadline: string|null; targetMetric?: { metric: string; direction?: "UP"|"DOWN"; target?: number|null }; status: "DRAFT"; approvedByHuman: false; createdAt: string; interpretation: { suggestedMissionType: string; risk: "R1"|"R2"|"R3"|"R4"; externalAction: boolean; label: "AI interpretation" } };
export function draftDirective(input: { department: DepartmentId; instruction: string; goal?: string; priority?: "A"|"B"|"C"; deadline?: string|null; targetMetric?: DepartmentDirectiveDraft["targetMetric"] }): DepartmentDirectiveDraft {
  const instruction = input.instruction.trim(); if (!instruction) throw new Error("INSTRUCTION_REQUIRED");
  const engineering = input.department === "engineering"; const fund = input.department === "fund";
  return { id: `directive-${Date.now().toString(36)}`, department: input.department, instruction: instruction.slice(0,2000), goal: input.goal?.trim().slice(0,500), priority: input.priority ?? "B", deadline: input.deadline ?? null, targetMetric: input.targetMetric, status: "DRAFT", approvedByHuman: false, createdAt: new Date().toISOString(), interpretation: { suggestedMissionType: engineering ? "ENGINEERING_REQUEST" : fund ? "FUND_RESEARCH" : `${input.department.toUpperCase()}_MISSION`, risk: engineering ? "R3" : fund ? "R1" : "R1", externalAction: engineering, label: "AI interpretation" } };
}
