"use client";

import { useCallback, useEffect, useState } from "react";
import type { DepartmentId } from "@/app/lib/mobile-ceo/departments";
import { DepartmentChat } from "./DepartmentChat";

export type EmployeeReadModel = { id: string; name: string; role: string; departmentId: DepartmentId; riskLevel: string; status: string; currentMissionId?: string; currentMissionTitle?: string; skills: Array<{ id: string; name: string; status: string; category: string }> };
const STATUS: Record<string, string> = { IDLE: "待機中", THINKING: "作業中", RESEARCHING: "作業中", EXECUTING: "作業中", REVIEWING: "レビュー中", WAITING_APPROVAL: "CEO確認待ち", COMPLETE: "完了", ERROR: "問題あり", UNKNOWN: "UNKNOWN" };

export function EmployeeWorkspace({ departmentId }: { departmentId: DepartmentId }) {
  const [employees, setEmployees] = useState<EmployeeReadModel[]>([]);
  const [selected, setSelected] = useState<EmployeeReadModel | null>(null);
  const [tab, setTab] = useState<"overview" | "work" | "skills" | "chat">("overview");
  const load = useCallback(async () => { const response = await fetch(`/api/company/departments/${departmentId}/employees`); if (response.ok) setEmployees((await response.json()).employees ?? []); }, [departmentId]);
  useEffect(() => { void load(); }, [load]);
  return <>
    {employees.length ? <section aria-labelledby="employees-title" className="rounded-2xl border border-slate-800 bg-slate-900/70 p-4"><h2 id="employees-title" className="font-bold">AI社員</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{employees.map((employee) => <button key={employee.id} type="button" onClick={() => { setSelected(employee); setTab("overview"); }} className="min-h-24 rounded-xl border border-slate-700 bg-slate-950/60 p-3 text-left"><strong className="block">{employee.name}</strong><span className="mt-2 block text-xs text-slate-400">● {STATUS[employee.status] ?? employee.status}</span><span className="mt-1 block truncate text-xs text-slate-500">現在: {employee.currentMissionTitle ?? "確認できるMissionなし"}</span></button>)}</div></section> : null}
    {selected ? <div className="fixed inset-0 z-50 flex items-end justify-end bg-black/60 lg:items-stretch" role="dialog" aria-modal="true" aria-label={`${selected.name}の詳細`}><button type="button" aria-label="社員詳細を閉じる" onClick={() => setSelected(null)} className="absolute inset-0"/><aside className="relative z-10 max-h-[92vh] w-full overflow-y-auto rounded-t-3xl border border-slate-700 bg-[#0b1020] p-4 lg:h-full lg:max-h-none lg:max-w-md lg:rounded-none"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-slate-400">{selected.role}</p></div><button type="button" onClick={() => setSelected(null)} className="min-h-11 min-w-11 rounded-xl border border-slate-700">×</button></div><div className="mt-4 grid grid-cols-4 gap-1" role="tablist">{([['overview','概要'],['work','仕事'],['skills','Skills'],['chat','Chat']] as const).map(([id,label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`min-h-11 rounded-lg text-xs ${tab === id ? "bg-violet-600" : "bg-slate-800"}`}>{label}</button>)}</div><div className="mt-4">{tab === "overview" ? <dl className="space-y-3 text-sm"><div><dt className="text-slate-500">Status</dt><dd>{STATUS[selected.status] ?? selected.status}</dd></div><div><dt className="text-slate-500">Role</dt><dd>{selected.role}</dd></div><div><dt className="text-slate-500">Department</dt><dd>{selected.departmentId}</dd></div><div><dt className="text-slate-500">Risk Level</dt><dd>{selected.riskLevel}</dd></div><div><dt className="text-slate-500">Current Mission</dt><dd>{selected.currentMissionTitle ?? "UNKNOWN"}</dd></div></dl> : null}{tab === "work" ? <div className="rounded-xl bg-slate-900 p-3 text-sm"><p className="text-slate-500">Current Mission</p><p className="mt-1">{selected.currentMissionTitle ?? "UNKNOWN"}</p><p className="mt-3 text-xs text-slate-500">実在するMissionのみ表示しています。</p></div> : null}{tab === "skills" ? <ul className="space-y-2">{selected.skills.length ? selected.skills.map((skill) => <li key={skill.id} className="rounded-xl border border-slate-700 p-3 text-sm"><strong>{skill.name}</strong><p className="mt-1 text-xs text-slate-400">{skill.status} · {skill.category}</p></li>) : <li className="text-sm text-slate-400">割り当て済みSkillはありません。</li>}</ul> : null}{tab === "chat" ? <DepartmentChat id={departmentId} label={selected.name} secretaryId={selected.id} onDirective={() => setSelected(null)}/> : null}</div></aside></div> : null}
  </>;
}
