import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
const read = (file) => fs.readFileSync(path.join(process.cwd(), file), "utf8");

test("Sidebar permanently exposes Memo and Settings separately from Knowledge", () => { const nav = read("app/lib/config/navigation.ts"); const sidebar = read("components/app-shell/AppSidebar.tsx"); assert.match(nav, /id: "knowledge", label: "知識"/); assert.match(nav, /label: "設定"/); assert.match(sidebar, />メモ</); assert.match(sidebar, /mt-auto/); });
test("Department Workspace renders real employees, drawer tabs and floating contextual chat", () => { const page = read("components/mobile-ceo/DepartmentPage.tsx"); const employee = read("components/mobile-ceo/EmployeeWorkspace.tsx"); const overlay = read("components/app-shell/WorkspaceOverlays.tsx"); assert.match(page, /EmployeeWorkspace/); for (const label of ["概要","仕事","Skills","Chat"]) assert.ok(employee.includes(label)); assert.match(employee, /role="dialog"/); assert.match(overlay, /DepartmentChat/); assert.match(overlay, /bottom-20/); });
test("Employee Read Model comes from Registry, Mission state and Skill Registry", () => { const route = read("app/api/company/departments/[id]/employees/route.ts"); assert.match(route, /findSecretary/); assert.match(route, /computeAgentStatuses/); assert.match(route, /getSkillsForSecretary/); });
test("Quick Memo is same-origin, idempotent and remains Inbox capture", () => { const route = read("app/api/company/memo/route.ts"); assert.match(route, /isSameOriginMutation/); assert.match(route, /claimIdempotency\("quick-memo"/); assert.match(route, /captureToInbox/); assert.doesNotMatch(route, /promote|saveKnowledge/); });
test("Notification delivery is derived, deduplicated and failure-isolated", () => { const router = read("app/lib/notifications/router.ts"); const cycle = read("app/lib/company/runtime/autonomousCycle.ts"); assert.match(router, /notification-delivery/); assert.match(router, /fingerprint/); assert.match(cycle, /deliverNotifications[\s\S]*\.catch/); });
test("Engineering PR Ready, CI Failure and Blocked are notification sources", () => { const route = read("app/api/engineering/requests/route.ts"); const events = read("app/lib/notifications/events.ts"); assert.match(route, /notificationSources/); assert.match(events, /ENGINEERING_PR_READY/); assert.match(events, /ENGINEERING_CI_FAILURE/); assert.match(events, /ENGINEERING_BLOCKED/); });
test("Slack approval verifies signature, authorized user, idempotency and server-side Approval", () => { const route = read("app/api/integrations/slack/actions/route.ts"); assert.match(route, /verifySlackRequest/); assert.match(route, /isAuthorizedSlackUser/); assert.match(route, /snapshot\.state\.approvals\.find/); assert.match(route, /claimIdempotency\("slack-approval"/); assert.match(route, /canApproveInSlack/); });
test("R3/R4 and investment safety cannot be bypassed by Slack", () => { const slack = read("app/lib/notifications/slack.ts"); const action = read("app/api/integrations/slack/actions/route.ts"); const types = read("app/lib/company/execution/actionTypes.ts"); assert.match(slack, /\["R0", "R1", "R2"\]/); assert.match(action, /R3\/R4はSlackから承認できません/); assert.match(types, /INVESTMENT_TRADE[\s\S]*R4/); });
test("mobile remains five items and 375px sheets avoid fixed wide layout", () => { const shell = read("components/app-shell/AppShell.tsx"); const files = shell + read("components/app-shell/WorkspaceOverlays.tsx") + read("components/mobile-ceo/EmployeeWorkspace.tsx"); for (const label of ["ホーム","事業部","＋","承認","秘書"]) assert.ok(shell.includes(label)); assert.doesNotMatch(files, /min-w-\[(?:376|[4-9]\d\d)px\]/); assert.match(files, /min-h-11/); });
