import test from "node:test"; import assert from "node:assert/strict"; import fs from "node:fs"; import path from "node:path"; import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."); const read=(p)=>fs.readFileSync(path.join(root,p),"utf8");
test("Department pages share mobile cards and 44px directive controls",()=>{const ui=read("components/mobile-ceo/DepartmentPage.tsx"); assert.match(ui,/grid grid-cols-2/); assert.match(ui,/min-h-11/); assert.doesNotMatch(ui,/min-w-\[(?:376|[4-9]\d\d)px\]/);});
test("Directive approval requires human confirmation, same origin and idempotency",()=>{const route=read("app/api/company/directives/approve/route.ts"); assert.match(route,/confirmedByHuman !== true/); assert.match(route,/isSameOriginMutation/); assert.match(route,/department-directive/);});
test("Directive draft is durable and approval resolves it server-side",()=>{const draft=read("app/api/company/directives/draft/route.ts"); const approve=read("app/api/company/directives/approve/route.ts"); assert.match(draft,/department-directive-draft/); assert.match(draft,/draftId: directive\.id/); assert.match(approve,/getIdempotencyResult<\{ directive: DepartmentDirectiveDraft \}>\("department-directive-draft", body\.draftId\)/); assert.match(approve,/CLIENT_DRAFT_TAMPERING_REJECTED/); assert.doesNotMatch(approve,/const d = body\.directive/);});
test("Fund Directive is research-only and cannot execute trades",()=>{const route=read("app/api/company/directives/approve/route.ts"); const model=read("app/lib/mobile-ceo/departments.ts"); assert.match(model,/missionType: "FUND_RESEARCH"/); assert.match(model,/"RESEARCH_ANALYSIS_ONLY"/); assert.match(model,/"INVESTMENT_TRADE_R4"/); assert.doesNotMatch(route,/placeOrder|submitOrder|executeTrade/);});
test("Creator Directive cannot route directly to external publish",()=>{const model=read("app/lib/mobile-ceo/departments.ts"); assert.match(model,/"DRAFT_OR_RESEARCH_ONLY"/); assert.match(model,/"EXTERNAL_PUBLISH_REQUIRES_SEPARATE_HUMAN_APPROVAL"/);});
test("Engineering Directive reuses human-confirmed intake and cannot merge",()=>{const route=read("app/api/company/directives/approve/route.ts"); assert.match(route,/createEngineeringRequest/); assert.match(route,/confirmedByHuman: true/); assert.doesNotMatch(route,/pr merge|mergePullRequest|autoMerge/);});
test("Financial HUMAN_ONLY remains explicit",()=>{const model=read("app/lib/mobile-ceo/departments.ts"); assert.match(model,/executionAuthority: "HUMAN_ONLY"/); assert.match(model,/aiExecutionAllowed: false/);});
