"use client";
import { useCallback, useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import type { ConnectionHealth } from "@/app/lib/system/connections";

const labels: Record<string,string> = { connected:"正常", warning:"要確認", disconnected:"接続なし", not_configured:"未設定", unknown:"確認できません" };
const colors: Record<string,string> = { connected:"text-emerald-400", warning:"text-amber-400", disconnected:"text-rose-400", not_configured:"text-slate-500", unknown:"text-slate-400" };
export function ConnectionsDashboard() {
  const [services,setServices] = useState<ConnectionHealth[]>([]); const [selected,setSelected] = useState<ConnectionHealth|null>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState("");
  const load = useCallback(async (test=false) => { setLoading(true); setError(""); try { const response = await fetch("/api/system/connections", { method: test ? "POST" : "GET" }); const json = await response.json(); if (!response.ok) throw new Error(json.error); setServices(json.services); setSelected((current) => json.services.find((item:ConnectionHealth) => item.service === current?.service) ?? json.services[0] ?? null); } catch(e) { setError(e instanceof Error ? e.message : "確認できません"); } finally { setLoading(false); } },[]);
  useEffect(() => { load(); },[load]); const healthy=services.filter((s)=>s.status==="connected").length; const warning=services.filter((s)=>s.status==="warning").length;
  return <main className="min-h-screen px-4 py-16 sm:px-7 lg:py-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-violet-300">System</p><h1 className="text-3xl font-bold">AI Company Health</h1><p className="mt-2 text-sm text-slate-400">{services.length || 7}サービス中 · <span className="text-emerald-400">{healthy} 正常</span> · <span className="text-amber-400">{warning} 要確認</span></p></div><button onClick={()=>load(true)} disabled={loading} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-medium"><RefreshCw className={`mr-2 inline h-4 w-4 ${loading?"animate-spin":""}`} />接続テストを実行</button></header>{error&&<p className="mt-5 rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-rose-300">{error}</p>}<div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><section className="grid gap-3 sm:grid-cols-2">{services.map((service)=><button key={service.service} onClick={()=>setSelected(service)} className={`rounded-2xl border p-5 text-left transition ${selected?.service===service.service?"border-violet-500 bg-violet-500/10":"border-slate-800 bg-slate-900/60"}`}><div className="flex items-start justify-between"><span className="text-2xl">{service.icon}</span><span className={`text-xs ${colors[service.status]}`}>● {labels[service.status]}</span></div><h2 className="mt-4 font-semibold">{service.label}</h2><p className="mt-1 text-sm text-slate-400">{service.message}</p>{service.itemCount!=null&&<p className="mt-3 text-xs text-slate-500">{service.itemCount.toLocaleString()}件</p>}</button>)}</section><aside className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5 xl:sticky xl:top-6 xl:h-fit">{selected?<><div className="flex items-center gap-3"><span className="text-3xl">{selected.icon}</span><div><h2 className="text-xl font-semibold">{selected.label}</h2><p className={colors[selected.status]}>● {labels[selected.status]}</p></div></div><dl className="mt-6 space-y-4 text-sm"><div><dt className="text-xs text-slate-500">状態</dt><dd className="mt-1 text-slate-200">{selected.message}</dd></div><div><dt className="text-xs text-slate-500">最終チェック</dt><dd className="mt-1 text-slate-300">{new Date(selected.lastCheckedAt).toLocaleString("ja-JP")}</dd></div>{selected.action&&<div><dt className="text-xs text-slate-500">やること</dt><dd className="mt-1 rounded-lg bg-amber-500/10 p-3 text-amber-200">{selected.action}</dd></div>}{selected.detail&&<details><summary className="cursor-pointer text-xs text-slate-500">詳細情報</summary><p className="mt-2 break-words rounded-lg bg-slate-950 p-3 text-xs text-slate-400">{selected.detail}</p></details>}</dl></>:<p className="text-slate-500">サービスを選択してください。</p>}</aside></div></div></main>;
}
