import { vaultDocumentStore } from "../persistence/vaultStore";
import { supabaseKnowledgeIndexRepository } from "../persistence/supabase/knowledgeIndexRepository";
import { syncStatusRepository, type SystemSyncStatus } from "../persistence/supabase/syncStatusRepository";
import { getRedisClient, isRedisAvailable } from "../utils/redis";
import { countScheduled, isBufferConfigured } from "../note/publishing/buffer";
import type { ConnectionHealth, ConnectionStatus } from "./connections";
import { readVaultKnowledgeIndexRecords } from "../knowledge/indexSync";

const now = () => new Date().toISOString();
const health = (service: string, label: string, icon: string, status: ConnectionStatus, message: string, extra: Partial<ConnectionHealth> = {}): ConnectionHealth => ({ service, label, icon, status, message, lastCheckedAt: now(), ...extra });
async function checkVault(indexStatus?: SystemSyncStatus) { try { let itemCount: number | null = null; if (supabaseKnowledgeIndexRepository.configured() && indexStatus?.status === "connected" && indexStatus.last_sync_at) { try { itemCount = await supabaseKnowledgeIndexRepository.count(); } catch { itemCount = null; } } if (itemCount == null) itemCount = (await readVaultKnowledgeIndexRecords()).length; return health("vault","Obsidian / Vault","🧠","connected","Knowledgeを読み取れます",{ itemCount, lastSuccessAt: now() }); } catch (e) { return health("vault","Obsidian / Vault","🧠","disconnected","Vaultを読み取れません",{ detail: e instanceof Error ? e.message : undefined, action: "Vault設定を確認してください" }); } }
async function checkGithub() { if (!process.env.GITHUB_TOKEN || !process.env.GITHUB_OWNER || !process.env.GITHUB_REPO) return health("github","GitHub Vault","◈","not_configured","GitHub Vaultは未設定です"); try { const response = await fetch(`https://api.github.com/repos/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}`, { headers: { Authorization: `Bearer ${process.env.GITHUB_TOKEN}`, Accept: "application/vnd.github+json" }, cache: "no-store" }); return response.ok ? health("github","GitHub Vault","◈","connected","Vault履歴へ接続できます",{ lastSuccessAt: now() }) : health("github","GitHub Vault","◈","warning","GitHubへの接続を確認してください",{ detail: `HTTP ${response.status}` }); } catch (e) { return health("github","GitHub Vault","◈","unknown","GitHubの状態を確認できません",{ detail: e instanceof Error ? e.message : undefined }); } }
async function checkSupabase() { if (!supabaseKnowledgeIndexRepository.configured()) return health("supabase","Supabase","⚡","not_configured","高速Knowledge Indexは未設定です"); try { const count = await supabaseKnowledgeIndexRepository.count(); return health("supabase","Supabase","⚡","connected","Knowledge Indexへ接続できます",{ itemCount: count ?? undefined, lastSuccessAt: now() }); } catch (e) { return health("supabase","Supabase","⚡","warning","高速Indexを利用できません（Vault検索は利用可能）",{ detail: e instanceof Error ? e.message : undefined }); } }
async function checkRedis() { if (!isRedisAvailable) return health("redis","Redis","◆","not_configured","Runtime State用Redisは未設定です"); try { await getRedisClient()!.ping(); return health("redis","Redis","◆","connected","Runtime Stateへ接続できます",{ lastSuccessAt: now() }); } catch (e) { return health("redis","Redis","◆","disconnected","Runtime Stateへ接続できません",{ detail: e instanceof Error ? e.message : undefined }); } }
async function checkBuffer() { if (!isBufferConfigured()) return health("buffer","Buffer / X","𝕏","not_configured","Buffer / Xは未設定です"); const result = await countScheduled(); return result.ok ? health("buffer","Buffer / X","𝕏","connected","X予約キューへ接続できます",{ itemCount: result.data, lastSuccessAt: now() }) : health("buffer","Buffer / X","𝕏",result.error.kind === "auth" ? "disconnected" : "warning",result.error.message,{ detail: result.error.hint }); }
async function checkSlack() { const token = process.env.SLACK_BOT_TOKEN; if (!token && !process.env.SLACK_WEBHOOK_URL) return health("slack","Slack","💬","not_configured","Slackは未設定です"); if (!token) return health("slack","Slack","💬","connected","Webhookが設定されています"); try { const response = await fetch("https://slack.com/api/auth.test", { method: "POST", headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json() as { ok?: boolean; error?: string }; return body.ok ? health("slack","Slack","💬","connected","Slackへ接続できます",{ lastSuccessAt: now() }) : health("slack","Slack","💬","warning","Slack認証を確認してください",{ detail: body.error }); } catch (e) { return health("slack","Slack","💬","unknown","Slackの状態を確認できません",{ detail: e instanceof Error ? e.message : undefined }); } }
async function checkRunner(stored?: SystemSyncStatus) { if (!process.env.LOCAL_RUNNER_TOKEN) return health("note_runner","note Runner","▶","not_configured","note Runnerは未設定です"); const last = stored?.last_success_at ?? undefined; if (!last) return health("note_runner","note Runner","▶","unknown","最終接続時刻を取得できません",{ action: "Mac上のRunnerを確認してください" }); const hours = (Date.now() - new Date(last).getTime()) / 3_600_000; return hours > 4 ? health("note_runner","note Runner","▶","warning",`note Runnerが${Math.floor(hours)}時間接続されていません`,{ detail: last, action: "Macを起動しRunnerを開始してください" }) : health("note_runner","note Runner","▶","connected","note Runnerは最近接続しました",{ lastSuccessAt: last }); }
export async function checkAllConnections(): Promise<ConnectionHealth[]> { let stored: SystemSyncStatus[] = []; if (syncStatusRepository.configured()) { try { stored = await syncStatusRepository.list(); } catch { /* status table failure must not break health UI */ } } return Promise.all([checkVault(stored.find((item) => item.service === "knowledge_index")),checkGithub(),checkSupabase(),checkRedis(),checkBuffer(),checkRunner(stored.find((item) => item.service === "note_runner")),checkSlack()]); }
