import { createHash, randomUUID } from "node:crypto";
import type { DepartmentResearchPolicy, ResearchArtifact, ResearchCoverageGap, ResearchHealth, ResearchItem, ResearchProvider, ResearchProviderItem, ResearchRun } from "./types";

const SECRET_KEYS = /(?:password|secret|token|credential|api[-_]?key|rawPrompt|rawChat|fullContent)/i;
const cleanUrl = (value?: string) => { if (!value) return undefined; try { const url = new URL(value); url.hash = ""; [...url.searchParams.keys()].filter((key) => /^(utm_|fbclid|gclid)/i.test(key)).forEach((key) => url.searchParams.delete(key)); return url.toString(); } catch { return undefined; } };
const cleanText = (value: string, max: number) => value.replace(/(?:bearer\s+|sk-|gh[opusr]_)[A-Za-z0-9_.-]+/gi, "[REDACTED]").slice(0, max);
export async function withinRuntimeBudget<T>(work:Promise<T>,remainingMs:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([work,new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error("RESEARCH_RUNTIME_BUDGET_EXCEEDED")),remainingMs);timer.unref?.();})]);}finally{if(timer)clearTimeout(timer);}}
export function researchFingerprint(item: Pick<ResearchProviderItem, "sourceUrl" | "sourceName" | "title" | "publishedAt">) { return createHash("sha256").update(cleanUrl(item.sourceUrl) ?? `${item.sourceName ?? "unknown"}|${item.title.trim().toLowerCase()}|${item.publishedAt?.slice(0,10) ?? "unknown"}`).digest("hex"); }
export function toResearchItem(input: ResearchProviderItem, context: { departmentId: string; researcherAgentId: string; topic: string; sourceType: ResearchItem["sourceType"]; fetchedAt: Date; freshnessHours: number }): ResearchItem {
  const published = input.publishedAt ? Date.parse(input.publishedAt) : NaN; const age = Number.isFinite(published) ? context.fetchedAt.getTime() - published : NaN;
  const freshnessStatus = Number.isFinite(age) ? age <= context.freshnessHours * 3_600_000 ? "FRESH" : "STALE" : "UNKNOWN";
  const fingerprint = researchFingerprint(input);
  return { id: `research_${fingerprint.slice(0,20)}`, departmentIds: [context.departmentId], researcherAgentId: context.researcherAgentId, topic: cleanText(context.topic, 120), title: cleanText(input.title, 240), summary: cleanText(input.summary, 1200), sourceType: context.sourceType, sourceUrl: cleanUrl(input.sourceUrl), sourceName: input.sourceName ? cleanText(input.sourceName, 120) : undefined, publishedAt: input.publishedAt, fetchedAt: context.fetchedAt.toISOString(), freshnessStatus, reliability: input.reliability ?? "UNKNOWN", tags: (input.tags ?? []).filter((tag) => !SECRET_KEYS.test(tag)).slice(0,20), relatedKnowledgeIds: (input.relatedKnowledgeIds ?? []).slice(0,50), fingerprint, conflictStatus: "NONE" };
}
export function dedupeResearch(existing: ResearchItem[], incoming: ResearchItem[], limit = 1000) { const map = new Map(existing.map((item) => [item.fingerprint, item])); let duplicates = 0; for (const item of incoming) { const prior = map.get(item.fingerprint); if (prior) { duplicates++; map.set(item.fingerprint, { ...prior, departmentIds: [...new Set([...prior.departmentIds, ...item.departmentIds])], fetchedAt: item.fetchedAt }); } else map.set(item.fingerprint, item); } return { items: [...map.values()].slice(-limit), duplicates }; }
export async function runDepartmentResearch(input: { policy: DepartmentResearchPolicy; providers: ResearchProvider[]; existingItems?: ResearchItem[]; now?: Date }): Promise<{ run: ResearchRun; items: ResearchItem[]; artifacts: ResearchArtifact[] }> {
  const now = input.now ?? new Date(); const run: ResearchRun = { id: `research_run_${randomUUID()}`, departmentId: input.policy.departmentId, researcherAgentId: input.policy.researcherAgentId, startedAt: now.toISOString(), queryCount: 0, fetchedCount: 0, acceptedCount: 0, duplicateCount: 0, staleCount: 0, checkedSources: [], successfulSources: [], failedSources: [], status: "RUNNING" };
  const deadline = Date.now() + input.policy.maxRuntimeMs; const raw: ResearchItem[] = [];
  for (const topic of input.policy.topics.slice(0,input.policy.maxQueriesPerRun)) { if (Date.now() >= deadline) break; run.queryCount++; const eligible = input.providers.filter((provider) => input.policy.sourceTypes.includes(provider.sourceType)); const settled = await Promise.allSettled(eligible.map(async (provider) => { const remaining=Math.max(1,deadline-Date.now()); const result=await withinRuntimeBudget(provider.search({ departmentId: input.policy.departmentId, researcherAgentId: input.policy.researcherAgentId, topic, maxItems: input.policy.maxItemsPerRun, allowedDomains:input.policy.allowedDomains,blockedDomains:input.policy.blockedDomains }),remaining); return {provider,result}; }));
    for (let index=0; index<settled.length; index++) { const result=settled[index]; run.checkedSources!.push(eligible[index].id); if (result.status === "rejected") { run.failedSources.push(eligible[index].id); continue; } run.successfulSources!.push(eligible[index].id); for (const item of result.value.result.items) raw.push(toResearchItem(item,{ departmentId: input.policy.departmentId,researcherAgentId: input.policy.researcherAgentId,topic,sourceType:result.value.provider.sourceType,fetchedAt:now,freshnessHours:input.policy.freshnessHours })); }
  }
  run.fetchedCount=raw.length; const merged=dedupeResearch(input.existingItems??[],raw.slice(0,input.policy.maxItemsPerRun)); run.duplicateCount=merged.duplicates; const acceptedFingerprints=new Set(raw.map((item)=>item.fingerprint)); const accepted=merged.items.filter((item)=>acceptedFingerprints.has(item.fingerprint)); run.acceptedCount=accepted.length; run.staleCount=accepted.filter((item)=>item.freshnessStatus==="STALE").length; run.completedAt=new Date().toISOString(); run.checkedSources=[...new Set(run.checkedSources)]; run.successfulSources=[...new Set(run.successfulSources)]; run.failedSources=[...new Set(run.failedSources)]; run.status=!run.checkedSources.length||!run.successfulSources.length?"FAILED":run.failedSources.length?"PARTIAL":"COMPLETED";
  const artifacts=[...new Set(accepted.map((item)=>item.topic))].map((topic):ResearchArtifact=>{const topicItems=accepted.filter((item)=>item.topic===topic);return {id:`research_artifact_${createHash("sha256").update(topicItems.map((item)=>item.fingerprint).sort().join(":")).digest("hex").slice(0,20)}`,topic,summary:topicItems.map((item)=>item.summary).join(" ").slice(0,1200),researchItemIds:topicItems.map((item)=>item.id),departmentContexts:{[input.policy.departmentId]:topic},usedBy:[],createdAt:now.toISOString()};});
  return { run, items: merged.items, artifacts };
}
export function researchHealth(departmentId:string,runs:ResearchRun[]|null,items:ResearchItem[]|null):ResearchHealth { if(!runs||!items)return {departmentId,status:"UNKNOWN",lastSuccessfulRun:null,lastPartialRun:null,lastFailure:null,freshItemCount:0,staleItemCount:0,providerFailures:[]}; const relevant=runs.filter((run)=>run.departmentId===departmentId); const latest=(status:ResearchRun["status"])=>relevant.filter((run)=>run.status===status).map((run)=>run.completedAt??run.startedAt).sort().at(-1)??null; const scoped=items.filter((item)=>item.departmentIds.includes(departmentId)); const last=relevant.at(-1); return {departmentId,status:!last?"UNKNOWN":last.status==="COMPLETED"?"HEALTHY":last.status==="PARTIAL"?"PARTIAL":"FAILED",lastSuccessfulRun:latest("COMPLETED"),lastPartialRun:latest("PARTIAL"),lastFailure:latest("FAILED"),freshItemCount:scoped.filter((item)=>item.freshnessStatus==="FRESH").length,staleItemCount:scoped.filter((item)=>item.freshnessStatus==="STALE").length,providerFailures:last?.failedSources??[]}; }

export function researchCoverageGaps(policy:DepartmentResearchPolicy,runs:ResearchRun[],items:ResearchItem[],now=new Date()):ResearchCoverageGap[]{const relevantRuns=runs.filter((run)=>run.departmentId===policy.departmentId);const latest=relevantRuns.at(-1);return policy.topics.map((topic)=>{const observed=items.filter((item)=>item.departmentIds.includes(policy.departmentId)&&item.topic===topic&&item.publishedAt).sort((a,b)=>String(b.publishedAt).localeCompare(String(a.publishedAt))).at(0);const timestamp=observed?.publishedAt??observed?.fetchedAt;const ageHours=timestamp?(now.getTime()-Date.parse(timestamp))/3_600_000:undefined;const providerAvailable=!latest?null:Boolean(latest.successfulSources?.length||(latest.status!=="FAILED"&&latest.failedSources.length===0));const status:ResearchCoverageGap["status"]=providerAvailable===null?"UNKNOWN":!providerAvailable?"UNKNOWN":ageHours===undefined?"MISSING":ageHours<=policy.freshnessHours?"HEALTHY":"STALE";return {departmentId:policy.departmentId,topic,expectedFreshnessHours:policy.freshnessHours,lastFreshAt:timestamp,ageHours,status,providerAvailable};});}

/**
 * Research Artifactの保持。Department cronの要約Artifactは直近 legacyLimit 件だけ残し、
 * Research & Intelligence の Canonical Artifact（topicKeyごとに1件・id固定で更新）は押し出さない。
 */
export function retainResearchArtifacts(artifacts: ResearchArtifact[], legacyLimit = 500): ResearchArtifact[] {
  const canonical = new Map<string, ResearchArtifact>();
  const legacy: ResearchArtifact[] = [];
  for (const artifact of artifacts) { if (artifact.intelligence) canonical.set(artifact.id, artifact); else legacy.push(artifact); }
  return [...legacy.slice(-legacyLimit), ...canonical.values()];
}
