import type { DepartmentResearchPolicy } from "./types";

export const DEPARTMENT_RESEARCH_POLICIES: DepartmentResearchPolicy[] = [
  { departmentId: "creator", enabled: true, researcherAgentId: "creator-research", topics: ["AI", "副業", "投資テーマ", "読書", "資産形成", "習慣", "競合Content", "SNS反応"], sourceTypes: ["web", "rss", "internal"], schedule: "daily", maxQueriesPerRun: 8, maxItemsPerRun: 40, maxRuntimeMs: 45_000, freshnessHours: 72, knowledgeDomains: ["creator", "content"], autoKnowledgeCandidate: true },
  { departmentId: "fund", enabled: true, researcherAgentId: "fund-research", topics: ["Market", "Macro", "Interest Rates", "Company Earnings", "Official IR", "Industry", "Portfolio Companies", "Watchlist Companies"], sourceTypes: ["market", "web", "api"], schedule: "weekdays", maxQueriesPerRun: 8, maxItemsPerRun: 40, maxRuntimeMs: 45_000, freshnessHours: 24, knowledgeDomains: ["fund"], autoKnowledgeCandidate: true },
  { departmentId: "operations", enabled: true, researcherAgentId: "executive-kaizen", topics: ["Runtime Errors", "Workflow Failures", "Agent Fallbacks", "Skill Failures", "UNKNOWN Frequency", "Human Rejects"], sourceTypes: ["runtime", "internal"], schedule: "hourly", maxQueriesPerRun: 6, maxItemsPerRun: 30, maxRuntimeMs: 20_000, freshnessHours: 6, knowledgeDomains: ["operations"], autoKnowledgeCandidate: true },
  { departmentId: "engineering", enabled: true, researcherAgentId: "engineering-worker", topics: ["GitHub Issues", "CI Failures", "Framework Releases", "Security Advisories", "Runtime Errors"], sourceTypes: ["github", "runtime", "web"], schedule: "daily", maxQueriesPerRun: 5, maxItemsPerRun: 25, maxRuntimeMs: 30_000, freshnessHours: 24, knowledgeDomains: ["engineering"], autoKnowledgeCandidate: true },
];
export const researchPolicy = (departmentId: string) => DEPARTMENT_RESEARCH_POLICIES.find((policy) => policy.departmentId === departmentId);
