import { createHash } from "node:crypto";
import type { CompanyImprovementCandidate } from "./operationalObservability";

export type EngineeringSpecificationSourceType = "NEW_SKILL" | "SKILL_IMPROVEMENT" | "COMPANY_IMPROVEMENT";
export type CompanyImprovementSpecification = { id:string;candidateId:string;sourceType:"COMPANY_IMPROVEMENT";title:string;problem:string;evidence:string[];acceptanceCriteria:string[];requiredTests:string[];constraints:string[];beforeSnapshot:Record<string,number|null>;status:"READY_FOR_HUMAN_REVIEW"|"APPROVED_FOR_ENGINEERING"|"REJECTED";createdAt:string;updatedAt:string;decision?:{actor:"ceo";decision:"APPROVED_FOR_ENGINEERING"|"REJECTED";decidedAt:string;reason?:string} };
export type CompanyImprovementHandoff = {candidateId:string;specificationId:string;githubIssueNumber:number;githubIssueUrl:string;createdAt:string;workerStatus:"WAITING_AI_READY"|"READY_FOR_WORKER"|"PR_READY"|"MERGED";aiReadyApprovedAt?:string;aiReadyApprovedBy?:"ceo";pullRequestNumber?:number;pullRequestUrl?:string;mergedAt?:string};
const hash=(value:string)=>createHash("sha256").update(value).digest("hex").slice(0,20);
export function createCompanyImprovementSpecification(candidate:CompanyImprovementCandidate,beforeSnapshot:Record<string,number|null>,now=new Date()):CompanyImprovementSpecification{if(candidate.status!=="APPROVED")throw new Error("APPROVED_COMPANY_CANDIDATE_REQUIRED");const at=now.toISOString();return{id:`company_improvement_spec_${hash(candidate.id)}`,candidateId:candidate.id,sourceType:"COMPANY_IMPROVEMENT",title:candidate.title,problem:candidate.problem,evidence:[...candidate.evidence],acceptanceCriteria:["The repeated factual signal is reduced without weakening existing safety boundaries","Before and after evidence is collected in comparable windows","All regression suites pass"],requiredTests:["Deterministic friction regression test","Human gate invariant test","Before/after measurement test"],constraints:["Never auto-add ai-ready","Never push main","Never auto merge","Never deploy production","Never weaken financial HUMAN_ONLY","Never auto publish Creator content","Never expose secrets"],beforeSnapshot:{...beforeSnapshot},status:"READY_FOR_HUMAN_REVIEW",createdAt:at,updatedAt:at};}
export function decideCompanyImprovementSpecification(spec:CompanyImprovementSpecification,decision:"APPROVED_FOR_ENGINEERING"|"REJECTED",reason?:string,now=new Date()):CompanyImprovementSpecification{if(spec.status!=="READY_FOR_HUMAN_REVIEW")throw new Error("SPECIFICATION_ALREADY_DECIDED");if(decision==="REJECTED"&&!reason?.trim())throw new Error("REJECTION_REASON_REQUIRED");const decidedAt=now.toISOString();return{...spec,status:decision,updatedAt:decidedAt,decision:{actor:"ceo",decision,decidedAt,reason:reason?.trim()}};}
export function assertCompanySpecificationCanCreateIssue(spec:CompanyImprovementSpecification){if(spec.status!=="APPROVED_FOR_ENGINEERING"||spec.decision?.actor!=="ceo")throw new Error("HUMAN_SPECIFICATION_APPROVAL_REQUIRED");}
export function companyImprovementIssueBody(spec:CompanyImprovementSpecification){const bullets=(values:string[])=>values.map((value)=>`- ${value}`).join("\n");return`## Goal\n\n${spec.problem}\n\n## Source\n\nCOMPANY_IMPROVEMENT ${spec.candidateId}\n\n## Evidence\n\n${bullets(spec.evidence)}\n\n## Before Snapshot\n\n\`\`\`json\n${JSON.stringify(spec.beforeSnapshot,null,2)}\n\`\`\`\n\n## Acceptance Criteria\n\n${bullets(spec.acceptanceCriteria)}\n\n## Required Tests\n\n${bullets(spec.requiredTests)}\n\n## Constraints\n\n${bullets(spec.constraints)}\n\nIssue creation does not grant ai-ready. A separate explicit human action is required.`;}
