import { createHash, randomUUID } from "node:crypto";

export type OperationalEventType = "API_ERROR" | "SLOW_REQUEST" | "REPEATED_4XX" | "AGENT_ERROR" | "AGENT_FALLBACK" | "ROUTING_FALLBACK" | "MISSION_FAILED" | "MISSION_BLOCKED" | "MISSION_CANCELLED" | "APPROVAL_REJECTED" | "APPROVAL_HOLD" | "MANUAL_OVERRIDE" | "REPEATED_CORRECTION" | "UNKNOWN_RESULT" | "SKILL_FAILURE" | "UI_FRICTION" | "RESEARCH_PROVIDER_FAILURE";
export type OperationalEvent = { id: string; type: OperationalEventType; departmentId?: string; agentId?: string; missionId?: string; route?: string; occurredAt: string; fingerprint: string; metadata: Record<string, string | number | boolean | null> };
export type ImprovementRisk = "R0" | "R1" | "R2" | "R3" | "R4";
export type CompanyImprovementCandidate = { id: string; patternFingerprint: string; category: "UX" | "WORKFLOW" | "AGENT" | "API" | "PERFORMANCE" | "RESEARCH" | "KNOWLEDGE" | "SKILL"; title: string; problem: string; evidence: string[]; affectedDepartmentIds: string[]; severity: "LOW" | "MEDIUM" | "HIGH"; risk: ImprovementRisk; suggestedAction: string; status: "PROPOSED" | "APPROVED" | "HOLD" | "REJECTED"; createdAt: string; updatedAt: string; executable: false; engineeringHandoffAllowed: false };
export type ImprovementMeasurement = { candidateId: string; metric: string; before: number | null; after: number | null; beforeWindow: { from: string; to: string }; afterWindow?: { from: string; to: string }; status: "IMPROVED" | "UNCHANGED" | "REGRESSED" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN"; causalConclusion: null };

const FORBIDDEN = /(?:raw.?chat|raw.?prompt|password|secret|token|credential|api.?key|full.?content|body)/i;
export const FRICTION_THRESHOLDS: Partial<Record<OperationalEventType,number>> = { API_ERROR:3, SLOW_REQUEST:5, REPEATED_4XX:5, RESEARCH_PROVIDER_FAILURE:3, REPEATED_CORRECTION:3, APPROVAL_REJECTED:3, APPROVAL_HOLD:3, AGENT_ERROR:3, AGENT_FALLBACK:5, ROUTING_FALLBACK:5, MISSION_BLOCKED:3, SKILL_FAILURE:3, UNKNOWN_RESULT:3, UI_FRICTION:3 };
function safeMetadata(metadata:Record<string,unknown>) { return Object.fromEntries(Object.entries(metadata).filter(([key,value])=>!FORBIDDEN.test(key)&&(["string","number","boolean"].includes(typeof value)||value===null)).map(([key,value])=>[key,typeof value==="string"?value.replace(/(?:bearer\s+|sk-|gh[opusr]_)[A-Za-z0-9_.-]+/gi,"[REDACTED]").slice(0,200):value])) as OperationalEvent["metadata"]; }
export function operationalEvent(input:Omit<OperationalEvent,"id"|"occurredAt"|"fingerprint"|"metadata">&{occurredAt?:string;metadata?:Record<string,unknown>}):OperationalEvent { const dimension=`${input.type}|${input.departmentId??""}|${input.agentId??""}|${input.route??""}|${String(input.metadata?.errorCode??input.metadata?.reasonCode??"")}`; return {id:`operational_${randomUUID()}`,type:input.type,departmentId:input.departmentId,agentId:input.agentId,missionId:input.missionId,route:input.route,occurredAt:input.occurredAt??new Date().toISOString(),fingerprint:createHash("sha256").update(dimension).digest("hex"),metadata:safeMetadata(input.metadata??{})}; }
export const appendOperationalEvent=(events:OperationalEvent[],event:OperationalEvent,limit=2000)=>[...events,event].slice(-limit);
const category=(event:OperationalEvent):CompanyImprovementCandidate["category"]=>event.type==="API_ERROR"?"API":event.type==="SLOW_REQUEST"?"PERFORMANCE":event.type==="RESEARCH_PROVIDER_FAILURE"?"RESEARCH":event.type==="SKILL_FAILURE"?"SKILL":event.type==="UI_FRICTION"||event.type==="REPEATED_CORRECTION"?"UX":event.type==="UNKNOWN_RESULT"?"KNOWLEDGE":event.type==="AGENT_FALLBACK"?"AGENT":"WORKFLOW";
export function discoverCompanyImprovementCandidates(events:OperationalEvent[],existing:CompanyImprovementCandidate[],thresholds=FRICTION_THRESHOLDS,now=new Date()):CompanyImprovementCandidate[]{const result=[...existing];const groups=new Map<string,OperationalEvent[]>();for(const event of events){const list=groups.get(event.fingerprint)??[];list.push(event);groups.set(event.fingerprint,list);}for(const [fingerprint,evidence] of groups){const first=evidence[0];const threshold=thresholds[first.type]??Number.POSITIVE_INFINITY;if(evidence.length<threshold)continue;const id=`company_improvement_${fingerprint.slice(0,20)}`;const at=now.toISOString();const factualEvidence=evidence.slice(-10).map((item)=>`${item.occurredAt}:${item.id}`);const index=result.findIndex((candidate)=>candidate.id===id);if(index>=0){result[index]={...result[index],evidence:factualEvidence,updatedAt:at,severity:evidence.length>=threshold*2?"HIGH":result[index].severity};continue;}result.push({id,patternFingerprint:fingerprint,category:category(first),title:`Repeated ${first.type}`,problem:`${first.type} occurred ${evidence.length} times for the same factual dimension.`,evidence:factualEvidence,affectedDepartmentIds:[...new Set(evidence.flatMap((item)=>item.departmentId?[item.departmentId]:[]))],severity:evidence.length>=threshold*2?"HIGH":"MEDIUM",risk:"R1",suggestedAction:"Human review is required before an Engineering Specification may be created.",status:"PROPOSED",createdAt:at,updatedAt:at,executable:false,engineeringHandoffAllowed:false});}return result;}
export function improvementMeasurement(candidateId:string,metric:string,before:number|null,beforeWindow:ImprovementMeasurement["beforeWindow"],after?:{value:number;window:{from:string;to:string};evidenceCount:number;lowerIsBetter?:boolean}):ImprovementMeasurement{let status:ImprovementMeasurement["status"]="INSUFFICIENT_EVIDENCE";if(after&&after.evidenceCount>=3&&before!==null){const delta=after.value-before;status=delta===0?"UNCHANGED":((after.lowerIsBetter??true)?delta<0:delta>0)?"IMPROVED":"REGRESSED";}return {candidateId,metric,before,after:after?.value??null,beforeWindow,afterWindow:after?.window,status,causalConclusion:null};}
