import { createHash, randomUUID } from "node:crypto";
import type { ExecutionMission } from "../execution/mission";
import type { SkillExecutionResult } from "../../skills/types";

export type SkillExecutionStatus = "SUCCESS" | "FAILED" | "NOT_AUTHORIZED" | "NOT_IMPLEMENTED" | "INVALID_OUTPUT";
export type SkillExecutionEvent = { id: string; skillId: string; agentId: string; missionId?: string; stepId?: string; executionSource: "mission" | "direct" | "workflow"; status: SkillExecutionStatus; startedAt: string; completedAt: string; durationMs: number; warningCount: number; errorCode?: string; knowledgeRefs?: string[] };
export type SkillImprovementCandidate = { id: string; skillId: string; reasonType: "HIGH_FAILURE_RATE" | "REPEATED_ERROR" | "LOW_USAGE" | "MISSION_BLOCK_CORRELATION"; evidence: { executionCount: number; successCount: number; failureCount: number; distinctMissionCount: number; errorCodes: string[] }; status: "PROPOSED" | "APPROVED" | "HOLD" | "REJECTED"; createdAt: string; updatedAt: string; executable: false; registryMutationAllowed: false; engineeringHandoffAllowed: false };
export type SkillEffectiveness = { skillId: string; availability: "CONFIRMED" | "UNKNOWN"; executionCount: number | null; successCount: number | null; failureCount: number | null; successRate: number | null; distinctMissionCount: number | null; agents: string[]; lastUsedAt: string | null; averageDurationMs: number | null; failureBreakdown: Record<string, number>; missionOutcomes: { succeeded: number; failed: number; blocked: number; unknown: number }; frequentlyUsedKnowledge: Array<{ id: string; count: number }>; causalConclusion: null };

const code = (result: SkillExecutionResult) => result.ok ? undefined : result.error === "SKILL_NOT_AUTHORIZED" || result.error?.includes("not permitted") ? "NOT_AUTHORIZED" : result.error === "SKILL_NOT_IMPLEMENTED" || result.error === "not implemented" ? "NOT_IMPLEMENTED" : result.error === "SKILL_HANDLER_NOT_REGISTERED" ? "HANDLER_MISSING" : result.error === "INVALID_SKILL_OUTPUT" ? "INVALID_OUTPUT" : result.error?.includes("Unknown skillId") || result.error === "UNKNOWN_SKILL" ? "UNKNOWN_SKILL" : "EXECUTION_FAILED";
export function skillExecutionEvent(input: { skillId: string; agentId: string; source: SkillExecutionEvent["executionSource"]; result: SkillExecutionResult; startedAt: Date; completedAt?: Date; missionId?: string; stepId?: string; knowledgeRefs?: string[] }): SkillExecutionEvent {
  const completed = input.completedAt ?? new Date(); const errorCode = code(input.result);
  const status: SkillExecutionStatus = input.result.ok ? "SUCCESS" : errorCode === "NOT_AUTHORIZED" ? "NOT_AUTHORIZED" : errorCode === "NOT_IMPLEMENTED" || errorCode === "HANDLER_MISSING" || errorCode === "UNKNOWN_SKILL" ? "NOT_IMPLEMENTED" : errorCode === "INVALID_OUTPUT" ? "INVALID_OUTPUT" : "FAILED";
  return { id: `skill_execution_${randomUUID()}`, skillId: input.skillId, agentId: input.agentId, missionId: input.missionId, stepId: input.stepId, executionSource: input.source, status, startedAt: input.startedAt.toISOString(), completedAt: completed.toISOString(), durationMs: Math.max(0, completed.getTime() - input.startedAt.getTime()), warningCount: input.result.warnings?.length ?? 0, errorCode, knowledgeRefs: input.knowledgeRefs?.slice(0, 50) };
}
export const appendSkillExecution = (events: SkillExecutionEvent[], event: SkillExecutionEvent, limit = 1000) => [...events, event].slice(-limit);
export function skillEffectiveness(skillId: string, events: SkillExecutionEvent[] | null, missions: ExecutionMission[] = []): SkillEffectiveness {
  if (events === null) return { skillId, availability: "UNKNOWN", executionCount: null, successCount: null, failureCount: null, successRate: null, distinctMissionCount: null, agents: [], lastUsedAt: null, averageDurationMs: null, failureBreakdown: {}, missionOutcomes: { succeeded: 0, failed: 0, blocked: 0, unknown: 0 }, frequentlyUsedKnowledge: [], causalConclusion: null };
  const matching = events.filter((event) => event.skillId === skillId); const success = matching.filter((event) => event.status === "SUCCESS").length; const failure = matching.length - success;
  const failureBreakdown: Record<string, number> = {}; const knowledge = new Map<string, number>();
  for (const event of matching) { if (event.errorCode) failureBreakdown[event.errorCode] = (failureBreakdown[event.errorCode] ?? 0) + 1; for (const id of event.knowledgeRefs ?? []) knowledge.set(id, (knowledge.get(id) ?? 0) + 1); }
  const missionIds = [...new Set(matching.flatMap((event) => event.missionId ? [event.missionId] : []))]; const missionOutcomes = { succeeded: 0, failed: 0, blocked: 0, unknown: 0 };
  for (const id of missionIds) { const status = missions.find((mission) => mission.id === id)?.status; if (status === "COMPLETED" || status === "done") missionOutcomes.succeeded++; else if (status === "FAILED") missionOutcomes.failed++; else if (status === "BLOCKED") missionOutcomes.blocked++; else missionOutcomes.unknown++; }
  return { skillId, availability: "CONFIRMED", executionCount: matching.length, successCount: success, failureCount: failure, successRate: matching.length ? success / matching.length : null, distinctMissionCount: missionIds.length, agents: [...new Set(matching.map((event) => event.agentId))], lastUsedAt: matching.map((event) => event.completedAt).sort().at(-1) ?? null, averageDurationMs: matching.length ? matching.reduce((sum, event) => sum + event.durationMs, 0) / matching.length : null, failureBreakdown, missionOutcomes, frequentlyUsedKnowledge: [...knowledge.entries()].map(([id, count]) => ({ id, count })).sort((a, b) => b.count - a.count), causalConclusion: null };
}
export function discoverSkillImprovementCandidates(skillIds: string[], events: SkillExecutionEvent[], existing: SkillImprovementCandidate[], now = new Date()): SkillImprovementCandidate[] {
  const result = [...existing];
  for (const skillId of skillIds) { const facts = skillEffectiveness(skillId, events); if ((facts.executionCount ?? 0) < 5 || (facts.failureCount ?? 0) < 3) continue; const repeated = Object.entries(facts.failureBreakdown).sort((a,b)=>b[1]-a[1])[0]; const reasonType = repeated?.[1] >= 3 ? "REPEATED_ERROR" : "HIGH_FAILURE_RATE"; const id = `skill_improvement_${createHash("sha256").update(`${skillId}:${reasonType}`).digest("hex").slice(0,20)}`; if (result.some((item) => item.id === id)) continue; const timestamp = now.toISOString(); result.push({ id, skillId, reasonType, evidence: { executionCount: facts.executionCount!, successCount: facts.successCount!, failureCount: facts.failureCount!, distinctMissionCount: facts.distinctMissionCount!, errorCodes: Object.keys(facts.failureBreakdown).sort() }, status: "PROPOSED", createdAt: timestamp, updatedAt: timestamp, executable: false, registryMutationAllowed: false, engineeringHandoffAllowed: false }); }
  return result;
}
